apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: system
    images.cnpg.io/os: bullseye
    images.cnpg.io/date: '20250915'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 13
      image: ghcr.io/maarlab-rethinking/postgresql:13.21-21-bullseye@sha256:6b98502e308dbaf0238e21bb5a2b108e9944c226769f2ace78d1c7f2d1be8e3a
    - major: 14
      image: ghcr.io/maarlab-rethinking/postgresql:14.18-21-bullseye@sha256:862acd7c164546b584b56e39fe17dec721ee88cd3cbb24a0edf25913c86b6cb5
    - major: 15
      image: ghcr.io/maarlab-rethinking/postgresql:15.13-21-bullseye@sha256:72a2e94c07d92d21c604016bb5c44ad10da7a2e4c54a6f5eb46bee48095704ca
    - major: 16
      image: ghcr.io/maarlab-rethinking/postgresql:16.9-21-bullseye@sha256:2aae12b31e138cb995387ee251d545929fbc08c26138a626c3f70a12bf06accb
    - major: 17
      image: ghcr.io/maarlab-rethinking/postgresql:17.5-21-bullseye@sha256:d593ec025ece2cd52d7f366ab8bb41191dfa197e19f79e36c12f8518abb73f37
    - major: 18
      image: ghcr.io/maarlab-rethinking/postgresql:18beta2-9-bullseye@sha256:74dd994446c30fff4e7aa6644aaa4a013c1d575b41bcf349ebc45e6f38165618
